Repository exercism/csharp-analyzer, pull requests merged in 2021-11, with the labels that each got.

#95 Create dependabot.yml
  .github/dependabot.yml
Labels: x:size/small

#116 🤖 Update `.dockerignore` file
  .dockerignore
Labels: x:size/tiny

#109 Add analyzer for weighing-machine
  .gitignore
  Excercism.Analyzers.CSharp.sln
  src/Exercism.Analyzers.CSharp/Analyzers/Shared/SharedComments.cs
  src/Exercism.Analyzers.CSharp/Analyzers/WeighingMachine/WeighingMachineAnalyzer.cs
  src/Exercism.Analyzers.CSharp/Analyzers/WeighingMachine/WeighingMachineComments.cs
  src/Exercism.Analyzers.CSharp/Analyzers/WeighingMachine/WeighingMachineSolution.cs
  src/Exercism.Analyzers.CSharp/Exercises.cs
  src/Exercism.Analyzers.CSharp/SolutionAnalyzer.cs
  src/Exercism.Analyzers.CSharp/Syntax/Comparison/SyntaxNodeComparer.cs
  src/Exercism.Analyzers.CSharp/Syntax/PropertyDeclarationSyntaxExtensions.cs
  src/Exercism.Analyzers.CSharp/Syntax/SyntaxNodeExtensions.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Exercism.Analyzers.CSharp.IntegrationTests.csproj
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/AcessIssue/FieldShouldBePrivate/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/AcessIssue/FieldShouldBePrivate/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/AcessIssue/PropertySetterNotPrivate/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/AcessIssue/PropertySetterNotPrivate/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Approve/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Approve/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyDisplayWeight/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyDisplayWeight/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyPrecision/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyPrecision/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyTareAdjustment/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyTareAdjustment/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyWeight/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingPropertyWeight/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingWeighingMachine/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/Invalid/MissingWeighingMachine/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/IsNotAutoProperty/PropertyPrecision/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/IsNotAutoProperty/PropertyPrecision/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/IsNotAutoProperty/PropertyTareAdjustment/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/IsNotAutoProperty/PropertyTareAdjustment/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/RoundMethodCalled/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/RoundMethodCalled/expected_analysis.json
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/UseInitializer/WeighingMachine.cs
  test/Exercism.Analyzers.CSharp.IntegrationTests/Solutions/WeighingMachine/UseInitializer/expected_analysis.json
Labels: x:size/large
